[[spi-errorrptslack]]
= ErrorReporting SPI for Jira
:_basedir: ../../../
:_imagesdir: images/
:generate_pdf:
:toc:

This module (`incode-module-errorrptjira-impl`) provides an implementation of Apache Isis' link:http://isis.apache.org/guides/rgsvc/rgsvc.html#_rgsvc_presentation-layer-spi_ErrorReportingService[`ErrorReportingService`] SPI.
Whenever an error page is displayed to the user, the implementation will automatically log the details in JIRA and provide the ticket reference to the end-user.


== API & Implementation

This module provides `ErrorReportingServiceForJira` domain service as an implementation of the `ErrorReportingService`:

[source,java]
----
public interface ErrorReportingService {
    Ticket reportError(final ErrorDetails errorDetails);
}
----

where the returned `Ticket` determines what is shown on the error page for the end-user.
In the case of this implementation:

[source,java]
----
public class Ticket implements Serializable {
    private final String reference;                     // <1>
    private final String userMessage;                   // <2>
    private final String details;                       // <3>
    private final StackTracePolicy stackTracePolicy;    // <4>
    private final String kittenUrl;                     // <5>
    ...
}
----
<1> the JIRA issue number, eg "SUP-1234"
<2> the main error message to display to the user.
This defaults to:

+
_"Our apologies, an error has occurred.  Support has been notified."_

+
but can be configured to something else if required (see below).

<3> optionally, additional details (shown in a smaller font).
This defaults to:

+
_"For more details, see JIRA issue: %s"_

+
(with the place holder holding the URL for the generated JIRA issue), but can be configured to something else if required (see below).

<4> whether the end user should be able to view the stack trace.
This implementation ALWAYS HIDES the stack trace.
<5> the URL of an image to display, if any.
This implementation never shows any image.




== How to configure/use

=== Classpath

Update your classpath by adding this dependency in your `dom` project's `pom.xml`:


[source,xml]
----
<dependency>
    <groupId>org.incode.module.errorrptjira</groupId>
    <artifactId>incode-module-errorrptjira-impl</artifactId>
</dependency>
----


Check for later releases by searching link:http://search.maven.org/#search|ga|1|incode-module-errorrptjira-impl[Maven Central Repo].





=== Configuration Properties

The following configuration properties are required (either in `isis.properties` or through the `AppManifest`); for example:

[source,properties]
----
isis.service.errorReporting.jira.username=XXXXXX
isis.service.errorReporting.jira.password=XXXXXX
isis.service.errorReporting.jira.base=https://mycompany.atlassian.net/
isis.service.errorReporting.jira.projectKey=PRODSUP
isis.service.errorReporting.jira.issueType="IT Help"
----

Optionally the message text and details can be changed:

[source,properties]
----
isis.service.errorReporting.jira.userMessage=...
isis.service.errorReporting.jira.detailsFormat=...
----

There currently is no mechanism to localize the message.

=== Bootstrapping

In the `AppManifest`, update its `getDependencies()` method, eg:

[source,java]
----
@Override
public Set<Module> getDependencies() {
    return Sets.newHashSet(
            ...
            new org.incode.module.errorrptjira.ErrorReportingJiraModule(),
            ...
    );
}
----




== Known issues

None known at this time.




== Dependencies

Maven can report modules dependencies using:

[source,bash]
----
mvn dependency:list -o -pl modules/spi/errorrptjira/impl -D excludeTransitive=true
----

which, excluding Apache Isis itself, returns these compile/runtime dependencies:

[source,bash]
----
com.fasterxml.jackson.core:jackson-databind:jar:2.8.0
----

