= java-mavendeps-isistesting
:_imagesdir: ./
:toc:


This module, for use within link:http://isis.apache.org[Apache Isis] applications, defines a module that can be used as a single dependency for a set of common testing libraries.
This reduces the size of the maven `pom.xml` file for that consuming module; it simply needs to reference _this_ module as a `<dependency>`.

The appropriate configuration is included in a `<profile>` which is automatically included in all builds.
This profile can be disabled using a Maven property.


== Input Properties

The plugin defines several optional properties:

[source,xml]
----
<properties>
    <isis.version>1.13.1</isis.version>
    <assertj-core.version>3.6.0</assertj-core.version>
    <hamcrest.version>1.3</hamcrest.version>
    <objenesis.version>2.2</objenesis.version>
</properties>
----

The module uses the values shown above by defaults; if required they can be overridden in the consuming module.



== How to Configure

To configure:

* add the following to the `pom.xml` of the module(s) containing tests: +
+
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.danhaywood.mavendeps</groupId>
        <artifactId>isistesting</artifactId>
        <version>0.0.2</version>
        <type>pom</type>
        <scope>test</scope>
    </dependency>
</dependencies>
----

* Override any input properties, if required (see above).


To disable the (profile contributed by this) pom, pass the following system property to `mvn`:

[source,bash]
----
mvn -Dskip.danhaywood-mavendeps-isistesting
----



== Known issues

None currently



== Change Log

* `0.0.2` - fixes `<description>` in `pom.xml`
* `0.0.1` - first release




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----




== Maven deploy notes

The module is deployed using Sonatype's OSS support (see
http://central.sonatype.org/pages/apache-maven.html[user guide] and http://www.danhaywood.com/2013/07/11/deploying-artifacts-to-maven-central-repo/[this blog post]).

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.2 \
              0.0.3-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the ``pgp-maven-plugin``'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master
git push origin 0.0.2
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the `autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
