[[lib-pdfbox]]
= PDFBox Library
:_basedir: ../../../
:_imagesdir: images/

This module (`isis-module-pdfbox`) provides a wrapper around link:https://pdfbox.apache.org[Apache PDFBox].



== How to configure/use

You can either use this module "out-of-the-box", or you can fork this repo and extend to your own requirements. 

To use "out-of-the-box":

* update your classpath by adding this dependency in your dom project's `pom.xml`: +
+
[source,xml]
----
<dependency>
    <groupId>org.isisaddons.module.pdfbox</groupId>
    <artifactId>isis-module-pdfbox-dom</artifactId>
    <version>1.14.0</version>
</dependency>
----

* update the `getModules()` method of your `AppManifest`: +
+
[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.isisaddons.module.pdfbox.dom.PdfBoxModule.class,
            ...
    );
}
----



=== Supporting encrypted PDFs

Encrypted PDFs can be handled by adding the optional link:http://www.bouncycastle.org/[Legion of the Bouncy Castle] encryption libraries.
These can be included in your Maven project using three or so dependencies.
At the time of writing these were:

[source,xml]
----
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.54</version>
</dependency>

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcmail-jdk15on</artifactId>
    <version>1.54</version>
</dependency>

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpkix-jdk15on</artifactId>
    <version>1.54</version>
</dependency>
----



See the link:https://pdfbox.apache.org/2.0/dependencies.html[PDFBox documentation] for the most up-to-date information.



== API

This module provides a single service, called `PdfBoxService`.
It has the following API:

[source,java]
----
@DomainService(nature = NatureOfService.DOMAIN)
public class PdfBoxService {

    public byte[] merge(byte[]... pdfByteArrays) throws IOException { }     // <1>

    public void merge(                                                      // <2>
            OutputStream outputStream,
            InputStream... inputStreams
        ) throws IOException { }
}
----
<1> merge an arbitrary number of PDFs, represented as arrays of bytes, to another byte array
<2> merge an arbitrary number of PDFs, represented as an input stream, to an output stream




== Known issues

None known at this time.

Do note however that stitching together large PDFs can be memory intensive.
This in part is because Apache Isis' `Blob` datatype is just a wrapper around a `byte[]` byte array, rather than some sort of stream.




=== Dependencies

In addition to Apache Isis, this module depends upon:

* link:https://pdfbox.apache.org[Apache PDFBox]

* (optionally) link:http://www.bouncycastle.org/[Legion of the Bouncy Castle], to handle encrypted PDFs.



