[[lib-docrendering-freemarker]]
= Freemarker Document Rendering Library
:_basedir: ../../../
:_imagesdir: images/
:generate_pdf:
:toc:

This module (`incode-module-docrendering-freemarker`) provides an implementation of the xref:../../dom/document/dom-document.adoc#[Document subdomain] module's `Renderer` interface using the xref:../../lib/freemarker/lib-freemarker.adoc#[freemarker library] module.


== API

The module provides the `RendererForFreemarker` class which implements `RendererFromCharsToChars`.
This can be used to render a document name, or to perform a "mail merge" for a text document, such as an HTML email.

The class is intended to be used as the `Renderer` implementation for a Document `RenderingStrategy`.
The `RenderingStrategyFSForFreemarker` fixture script can be used to create such an entity, eg:

[source,java]
----
public class RenderingStrategyFSForFreemarker extends RenderingStrategyFSAbstract {

    public static final String REF = "FMK";

    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "RendererForFreemarker Rendering Strategy",
                DocumentNature.CHARACTERS, DocumentNature.CHARACTERS,
                RendererForFreemarker.class, executionContext);
    }
}
----

The xref:../../dom/document/dom-document.adoc#[document subdomain] module also allows ``RenderingStrategy``s to be created from the UI; it will "discover" all `Renderer` implementations from the classpath.



== How to configure/use


=== Classpath

Update your classpath by adding this dependency in your dom project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>org.incode.example.docrendering</groupId>
    <artifactId>incode-example-docrendering-freemarker-dom</artifactId>
    <version>2.0.0-M1</version>
</dependency>
----



Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-docrendering-freemarker-dom[Maven Central Repo].

For instructions on how to use the latest `-SNAPSHOT`, see the xref:../../../pages/contributors-guide/contributors-guide.adoc#[contributors guide].



=== Bootstrapping

In the `AppManifest`, update its `getModules()` method:

[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.incode.example.docrendering.freemarker.FreemarkerDocRenderingModule.class,
    );
}
----




== Known issues

None known at this time.




== Dependencies

Maven can report modules dependencies using:

[source,bash]
----
mvn dependency:list -o -pl modules/dom/docrendering-freemarker/impl -D excludeTransitive=true
----

which, excluding Apache Isis itself, returns no direct compile/runtime dependencies:

From the Incode Platform it uses:

* xref:../../lib/base/lib-base.adoc#[base library] module
* xref:../../lib/freemarker/lib-freemarker.adoc#[freemarker library] module
* xref:../../dom/document/dom-document.adoc#[document example subdomain] module
