[[lib-docrendering-freemarker]]
= Freemarker Document Rendering Library
:_basedir: ../../../
:_imagesdir: images/


This module (`incode-module-docrendering-freemarker`) provides an implementation of the Incode http://github.com/incodehq/incode-module-document[Document] module's `Renderer` interface using the (non-ASF) http://github.com/isisaddons/isis-module-freemarker[Isis addons' freemarker] module.


== API

The module provides the `RendererForFreemarker` class which implements `RendererFromCharsToChars`.
This can be used to render a document name, or to perform a "mail merge" for a text document, such as an HTML email.

The class is intended to be used as the `Renderer` implementation for a Document `RenderingStrategy`.
The `RenderingStrategyFSForFreemarker` fixture script can be used to create such an entity, eg:

[source,java]
----
public class RenderingStrategyFSForFreemarker extends RenderingStrategyFSAbstract {

    public static final String REF = "FMK";

    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "RendererForFreemarker Rendering Strategy",
                DocumentNature.CHARACTERS, DocumentNature.CHARACTERS,
                RendererForFreemarker.class, executionContext);
    }
}
----

The Incode http://github.com/incodehq/incode-module-document[document] module also allows ``RenderingStrategy``s to be created from the UI; it will "discover" all `Renderer` implementations from the classpath.



== How to configure/use

You can either use this module "out-of-the-box", or you can fork this repo and extend to your own requirements. 

=== "Out-of-the-box"

To use "out-of-the-box":

* update your classpath by adding this dependency in your dom project's `pom.xml`: +
+
[source,xml]
----
<dependency>
    <groupId>org.incode.module.docrendering</groupId>
    <artifactId>incode-module-docrendering-freemarker-dom</artifactId>
    <version>1.14.0</version>
</dependency>
----

* in the `AppManifest`, update its `getModules()` method: +
+
[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.incode.module.docrendering.freemarker.dom.FreemarkerDocRenderingModule.class,
    );
}
----



Notes:

* Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-docrendering-freemarker-dom[Maven Central Repo].



==== "Out-of-the-box" (-SNAPSHOT)

If you want to use the current `-SNAPSHOT`, then the steps are the same as above, except:

* when updating the classpath, specify the appropriate -SNAPSHOT version:

[source,xml]
----
<version>1.14.0-SNAPSHOT</version>
----

* add the repository definition to pick up the most recent snapshot (we use the Cloudbees continuous integration service).  We suggest defining the repository in a `<profile>`:

[source,xml]
----
<profile>
    <id>cloudbees-snapshots</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>http://repository-estatio.forge.cloudbees.com/snapshot/</url>
            <releases>
                <enabled>false>/enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</profile>
----







== Known issues

None known at this time.




== Dependencies

TODO: to update.
