[[starter-app]]
= Starter App
:_basedir: ../../
:_imagesdir: images/


TODO: to update



The purpose of ...

== Structure

== Example Modules


== How to run the Demo App

TODO: out of date, this material copied from original READMEs.

The prerequisite software is:

* Java JDK 8
* http://maven.apache.org[maven 3] (3.3.x or later is recommended).

To build the demo app:

[source]
----
git clone https://github.com/incodehq/isis-module-communications.git
cd isis-module-communications
mvn clean install
----


To run the demo app:

[source]
----
mvn -pl webapp jetty:run
----

Then log on using user: `sven`, password: `pass`



== FlywayDB

TODO: as per the flywaydb, generate the schema

The app will bootstrap against an in-memory database, however it will be Flyway that sets up the database schema (rather than DataNucleus automatically creating the database as might normally be the case).
This is discussed in a little more detail xref:what-happens-during-bootstrapping[below].

Then log on using user: `sven`, password: `pass`



[[__domain-app_running-against-sql-server]]
== Running demo against SQL Server

To run the demo application against SQL Server (as opposed to inmemory):

* create a new and empty database, eg `securitydemo`, with corresponding user and password

* edit the `webapp/pom.xml` to include the sqljdbc4 driver

* edit the JDBC properties in `persistor.properties` file:
+
[source,properties]
----
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionDriverName=com.microsoft.sqlserver.jdbc.SQLServerDriver
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionURL=jdbc:sqlserver://127.0.0.1.1533;instance=.;databaseName=securitydemo
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionUserName=securitydemo
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionPassword=pass
----

* configure to auto-create schema/tables in empty database, by adding to `persistor_datanucleus.properties`: +
+
[source,properties]
----
isis.persistor.datanucleus.impl.datanucleus.schema.autoCreateAll=true
isis.persistor.datanucleus.impl.datanucleus.schema.validateTables=true
isis.persistor.datanucleus.impl.datanucleus.schema.validateConstraints=true
----



== Icons

The icons used in the domainapp are provided by https://icons8.com/[Icons8].

