package org.isisaddons.module.publishmq.soapsubscriber.demoobject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-06-19T10:18:44.104+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://isisaddons.org/module/publishmq/soapsubscriber/DemoObject/", name = "DemoObject")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoObject {

    @WebMethod(operationName = "Processed", action = "http://isisaddons.org/module/publishmq/soapsubscriber/DemoObject/Processed")
    @RequestWrapper(localName = "Processed", targetNamespace = "http://isisaddons.org/module/publishmq/soapsubscriber/DemoObject/", className = "org.isisaddons.module.publishmq.soapsubscriber.demoobject.Processed")
    @ResponseWrapper(localName = "ProcessedResponse", targetNamespace = "http://isisaddons.org/module/publishmq/soapsubscriber/DemoObject/", className = "org.isisaddons.module.publishmq.soapsubscriber.demoobject.ProcessedResponse")
    @WebResult(name = "out", targetNamespace = "")
    public String processed(
            @WebParam(name = "name", targetNamespace = "")
            String name,
            @WebParam(name = "description", targetNamespace = "")
            String description
    );
}
