CREATE TABLE "simple"."SimpleObject"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(40) NOT NULL,
    "notes" VARCHAR(4000) NULL,
    "version" TIMESTAMP NOT NULL,
    CONSTRAINT "SimpleObject_PK" PRIMARY KEY ("id")
)
;