[[usage-guide]]
= Usage Guide
:_basedir: ../../
:_imagesdir: images/


TODO: fix up, material below copied verbatim from original READMEs


== Forking the repo

If instead you want to extend this module's functionality, then we recommend that you fork this repo.  The repo is
structured as follows:

* `pom.xml` - parent pom
* `app` - the demo webapp's `AppManifest`
* `dom` - the module implementation, depends on Isis applib
* `fixture` - fixtures, holding a sample domain objects and fixture scripts; depends on `dom`
* `integtests` - integration tests for the module; depends on `fixture`
* `webapp` - demo webapp (see above screenshots); depends on `dom` and `fixture`

Only the `dom` project is released to Maven Central Repo.  The versions of the other modules are purposely left at
`0.0.1-SNAPSHOT` because they are not intended to be released.

Note that the module uses link:https://projectlombok.org/[Project Lombok].  To compile the code within your IDE you will
therefore require the appropriate Lombok plugin.  See the link:https://projectlombok.org/download.html[Lombok download page] for more information.



