SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO



CREATE TABLE [incodeAlias].[Alias](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[aliasTypeId] [varchar](30) NOT NULL,
	[aliasedStr] [varchar](2000) NOT NULL,
	[atPath] [varchar](255) NULL,
	[reference] [varchar](255) NOT NULL,
	[version] [bigint] NOT NULL,
 CONSTRAINT [Alias_PK] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [Alias_aliased_atPath_aliasTypeId_IDX] UNIQUE NONCLUSTERED
(
	[aliasedStr] ASC,
	[atPath] ASC,
	[aliasTypeId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




