SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO



CREATE TABLE [incodeNote].[Note](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[calendarName] [varchar](254) NULL,
	[content] [varchar](4000) NULL,
	[date] [date] NULL,
	[version] [bigint] NOT NULL,
 CONSTRAINT [Note_PK] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [Note_date_idx] ON [incodeNote].[Note]
(
	[date] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO





CREATE TABLE [incodeNote].[NotableLink](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[calendarName] [varchar](254) NULL,
	[date] [date] NULL,
	[notableStr] [varchar](2000) NOT NULL,
	[noteId] [bigint] NOT NULL,
 CONSTRAINT [NotableLink_PK] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [NotableLink_note_UNQ] UNIQUE NONCLUSTERED
(
	[noteId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [NotableLink_notable_IDX] ON [incodeNote].[NotableLink]
(
	[notableStr] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



ALTER TABLE [incodeNote].[NotableLink]  WITH CHECK ADD  CONSTRAINT [NotableLink_FK1] FOREIGN KEY([noteId])
REFERENCES [incodeNote].[Note] ([id])
GO
ALTER TABLE [incodeNote].[NotableLink] CHECK CONSTRAINT [NotableLink_FK1]
GO
