[[dom-country]]
= Country Subdomain
:_basedir: ../../../
:_imagesdir: images/
:generate_pdf:
:toc:

This module (`incode-module-country`) provides a `Country` and a `State` entity, for use as reference data.



== Example App

The module's functionality can be explored by running the xref:../../../quickstart/quickstart-with-example-usage.adoc#[quickstart with example usage] using the `org.incode.domainapp.example.app.modules.ExampleDomDomCountryAppManifest`.


== How to configure/use


=== Classpath

Update your classpath by adding this dependency in your dom project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>org.incode.module.country</groupId>
    <artifactId>incode-module-country-dom</artifactId>
    <version>1.14.0</version>
</dependency>
----

Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-country-dom[Maven Central Repo].

For instructions on how to use the latest `-SNAPSHOT`, see the xref:../../../pages/contributors-guide.adoc#[contributors guide].


=== Bootstrapping

In the `AppManifest`, update its `getModules()` method, eg:

[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.incode.module.country.dom.CountryModule.class,
    );
}
----



== Known issues

None known at this time.




== Dependencies

The module uses icons from link:https://icons8.com/[icons8].
There are other no third-party dependencies.




