= Incode Parent
:_basedir: ../
:_imagesdir: images/
:generate_pdf:

This module defines a standard parent POM that can be used as a parent for applications that use the Incode Platform modules.

Its primary purpose is to make it easy to use a set up link:https://github.com/odavid/maven-plugins[maven mixin]s within child POMs; specifically to hold the required `<pluginManagement>` so that versions of plugins are locked down.
The xref:../quickstart/quickstart.adoc#[quickstart app] inherits from this module.

See below for details of the maven mixins so configured.


== Contents

This parent POM defines `<properties>` and `<pluginManagement>` for the plugins defined in the following maven mixins:


[width="100%",cols="^2a,^1m,4a,8m",options="header"]
|====================
^|Module
^|Ver.
^|Description
^|Mixin to add

|https://github.com/danhaywood/java-mavenmixin-cucumberreporting[cucumber reporting]
|0.0.2
|Configures cucumber reporting plugin for BDD specs.
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>cucumberreporting</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-datanucleusenhance[datanucleus enhance]
|0.0.4
|Configures datanucleus:enhance (for JDO entities of DN modules) for production and test code
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>datanucleusenhance</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-docker[docker]
|0.0.3
|Configures docker to package images and upload to a docker registry (docker hub by default)
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>docker</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-enforcerrelaxed[enforcer relaxed]
|0.0.2
|Applies the maven enforcer plugin (but with relaxed dependency convergence) +
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>enforcerrelaxed</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-jettyconsole[jetty console]
|0.0.2
|Configure jetty-console plugin (to create a standalone version of a webapp)
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>jettyconsole</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-jettywar[jetty war]
|0.0.2
|Package up a webapp as a WAR file, and to allow the webapp to be run using the jetty maven plugin
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>jettywar</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-sourceandjavadoc[source and javadoc]
|0.0.2
|Provides the ability to run source, javadoc and jxr plugins (packaged as JAR files or report using `mvn site`)
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>sourceandjavadoc</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-standard[standard]
|0.0.3
|Defines the "standard" set of plugins (clean, compile, jar, install, site etc)
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>standard</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-surefire[surefire]
|0.0.4
|Run surefire plugin for unit, integration and/or (http://cucumber.io[Cucumber]) BDD specs.
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>surefire</artifactId> +
</mixin>

|https://github.com/danhaywood/java-mavenmixin-staticanalysis[static analysis]
|0.0.2
|Ability to run various static analysis plugins (checkstyle, pmd, findbugs, javancss, jdepend) as report `mvn site`
|<mixin> +
{nbsp}  <groupId>com.danhaywood.mavenmixin</groupId> +
{nbsp}  <artifactId>staticanalysis</artifactId> +
</mixin>

|====================





== How to Configure

To configure:

* inherit from this pom: +
+
[source,xml]
----
<parent>
    <groupId>org.incode</groupId>
    <artifactId>incode-parent</artifactId>
    <version>1.15.0</version>
</parent>
----
+
This has the effect of defining a number of `<properties>` (eg `${mavenmixin-surefire.version}`) and also the setting up the `<pluginManagement>` of all of the plugins referenced by the above maven mixins.

* optionally, override the `isis.version` :
+
[source,xml]
----
<properties>
    <isis.version>1.15.0</isis.version>
    ...
</properties>
----

* for each maven mixin required in the consuming module, just add the corresponding `<mixin>` to: +
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.github.odavid.maven.plugins</groupId>
            <artifactId>mixin-maven-plugin</artifactId>
            <version>0.1-alpha-39</version>
            <extensions>true</extensions>
            <configuration>
                <mixins>
                    ...                                         <!--1-->
                </mixins>
            </configuration>
        </plugin>
    </plugins>
</build>
----
<1> add in mixin reference here - just copy-n-paste from the fourth column of the above table,

For example, to enable the https://github.com/danhaywood/java-mavenmixin-surefire[surefire] mixin, just add:

[source,xml]
----
<mixin>
    <groupId>com.danhaywood.mavenmixin</groupId>
    <artifactId>surefire</artifactId>
</mixin>
----







== Dependencies

This mixin module relies on the link:https://github.com/odavid/maven-plugins[com.github.odavid.maven.plugins:mixin-maven-plugin], released under Apache License v2.0.



