[[lib-docrendering-xdocreport]]
= XDocReport Document Rendering Library
:_basedir: ../../../
:_imagesdir: images/
:generate_pdf:
:toc:

This module (`incode-module-docrendering-xdocreport`) provides an implementation of the xref:../../dom/document/dom-document.adoc#[Document subdomain] module's `Renderer` interface using the xref:../../lib/xdocreport/lib-xdocreport.adoc#[xdocreport library] module.


== API

The module provides two different implementations of `Renderer`:

* `RendererForXDocReportToDocx` which implements `RendererFromBytesToBytes`

** uses Freemarker to mail-merge a Word template document, returning the `byte[]` of the resultant Word document

* `RendererForXDocReportToPdf` which implements `RendererFromBytesToBytes`

** almost the same as the previous renderer, but returns a `byte[]` array of a PDF rather than a Word document.



These classes can be used as the `Renderer` implementation for a Document `RenderingStrategy`.
Subclasses of the `RenderingStrategyFSAbstract` fixture script can be used to create such an entity, eg:

* `RenderingStrategyFSForXDocReportToDocx` +
+
[source,java]
----
public class RenderingStrategyFSForXDocReportToDocx extends RenderingStrategyFSAbstract {
    public static final String REF = "XDD";
    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "XDocReport to .docx",
                DocumentNature.BYTES,
                DocumentNature.BYTES,
                RendererForXDocReportToDocx.class, executionContext);
    }
}
----

* `RenderingStrategyFSForXDocReportToPdf` +
+
[source,java]
----
public class RenderingStrategyFSForXDocReportToPdf extends RenderingStrategyFSAbstract {
    public static final String REF = "XDP";
    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "XDocReport to .pdf",
                DocumentNature.BYTES,
                DocumentNature.BYTES,
                RendererForXDocReportToPdf.class, executionContext);
    }
}
----


The xref:../../dom/document/dom-document.adoc#[document subdomain] module also allows ``RenderingStrategy``s to be created from the UI; it will "discover" all `Renderer` implementations from the classpath.




== How to configure/use

=== Classpath

Update your classpath by adding this dependency in your dom project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>org.incode.example.docrendering</groupId>
    <artifactId>incode-example-docrendering-xdocreport-dom</artifactId>
</dependency>
----


Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-docrendering-xdocreport-dom[Maven Central Repo].

For instructions on how to use the latest `-SNAPSHOT`, see the xref:../../../pages/contributors-guide/contributors-guide.adoc#[contributors guide].




=== Bootstrapping

In the `AppManifest`, update its `getModules()` method, eg:

[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.incode.example.docrendering.xdocreport.dom.XdocReportDocRenderingModule.class,
    );
}
----




== Known issues

None known at this time.




=== Dependencies

Maven can report modules dependencies using:


[source,bash]
----
mvn dependency:list -o -pl modules/dom/docrendering-xdocreport/impl -D excludeTransitive=true
----

which, excluding the Incode Platform and Apache Isis itself, returns no direct compile/runtime dependencies.

From the Incode Platform it uses:

* xref:../../lib/base/lib-base.adoc#[base library] module
* xref:../../lib/xdocreport/lib-xdocreport.adoc#[freemarker library] module
* xref:../../dom/document/dom-document.adoc#[document example subdomain] module
