[[lib-docrendering-xdocreport]]
= XDocReport Document Rendering Library
:_basedir: ../../../
:_imagesdir: images/

This module (`incode-module-docrendering-xdocreport`) provides an implementation of the Incode http://github.com/incodehq/incode-module-document[Document] module's `Renderer` interface using the (non-ASF) http://github.com/isisaddons/isis-module-xdocreport[Isis addons' xdocreport] module.


== API

The module provides two different implementations of `Renderer`:

* `RendererForXDocReportToDocx` which implements `RendererFromBytesToBytes`
** uses Freemarker to mail-merge a Word template document, returning the `byte[]` of the resultant Word document
* `RendererForXDocReportToPdf` which implements `RendererFromBytesToBytes`
** almost the same as the previous renderer, but returns a `byte[]` array of a PDF rather than a Word document.


These classes can be used as the `Renderer` implementation for a Document `RenderingStrategy`.
Subclasses of the `RenderingStrategyFSAbstract` fixture script can be used to create such an entity, eg:

* `RenderingStrategyFSForXDocReportToDocx` +
+
[source,java]
----
public class RenderingStrategyFSForXDocReportToDocx extends RenderingStrategyFSAbstract {
    public static final String REF = "XDD";
    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "XDocReport to .docx",
                DocumentNature.BYTES,
                DocumentNature.BYTES,
                RendererForXDocReportToDocx.class, executionContext);
    }
}
----

* `RenderingStrategyFSForXDocReportToPdf` +
+
[source,java]
----
public class RenderingStrategyFSForXDocReportToPdf extends RenderingStrategyFSAbstract {
    public static final String REF = "XDP";
    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "XDocReport to .pdf",
                DocumentNature.BYTES,
                DocumentNature.BYTES,
                RendererForXDocReportToPdf.class, executionContext);
    }
}
----


The Incode http://github.com/incodehq/incode-module-document[document] module also allows ``RenderingStrategy``s to be created from the UI; it will "discover" all `Renderer` implementations from the classpath.




== How to configure/use

You can either use this module "out-of-the-box", or you can fork this repo and extend to your own requirements.

=== "Out-of-the-box"

To use "out-of-the-box":

* update your classpath by adding this dependency in your dom project's `pom.xml`: +
+
[source,xml]
----
<dependency>
    <groupId>org.incode.module.docrendering</groupId>
    <artifactId>incode-module-docrendering-xdocreport-dom</artifactId>
    <version>1.14.0</version>
</dependency>
----

* in the `AppManifest`, update its `getModules()` method: +
+
[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.incode.module.docrendering.xdocreport.dom.XdocReportDocRenderingModule.class,
    );
}
----

Notes:

* Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-docrendering-xdocreport-dom[Maven Central Repo].



==== "Out-of-the-box" (-SNAPSHOT)

If you want to use the current `-SNAPSHOT`, then the steps are the same as above, except:

* when updating the classpath, specify the appropriate -SNAPSHOT version:

[source,xml]
----
<version>1.14.0-SNAPSHOT</version>
----

* add the repository definition to pick up the most recent snapshot (we use the Cloudbees continuous integration service).  We suggest defining the repository in a `<profile>`:

[source,xml]
----
<profile>
    <id>cloudbees-snapshots</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>http://repository-estatio.forge.cloudbees.com/snapshot/</url>
            <releases>
                <enabled>false>/enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</profile>
----






== Known issues

None known at this time.




=== Dependencies

TODO: to update


