[[committers-guide]]
= Committers Guide
:_basedir: ../../
:_imagesdir: images/
:toc:


This guide contains procedures to be performed by committers/maintainers of this codebase.



== Build process

To build the platform, see the xref:contributors-guide.adoc#[contributors' guide].



== Release process

This section describes the steps to release the platform to Maven central.
There are four stages:

* release the maven mixins

* release the modules

* recreate the quickstart archetype (referencing the just-released modules)

* release the quickstart archetype

The release process uses Sonatype's OSS support (see
link:http://central.sonatype.org/pages/apache-maven.html[user guide]); our thanks to them for providing this service.



=== Prereqs

First, set the `$INCODEREL` environment variable to the release.
Generally speaking this should correspond to the version of Apache Isis.

[source,bash]
----
export INCODEREL=1.15.1
export INCODENEXT=1.16.0-SNAPSHOT

env | grep ^INCODE
----




=== Release Maven Mixins

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source,bash]
----
pushd mavenmixins
sh release.sh $INCODEREL \
              $INCODENEXT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
popd
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the `pgp-maven-plugin`'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master
----

[NOTE]
====
The mavenmixins' `release.sh` does _not_ tag the repo; this is left until the modules have also been released.
====


If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the parent `pom.xml`, the `nexus-staging-maven-plugin` has the
`autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].


=== Release Modules

The modules are released using their own `release.sh` script.
This is very similar to that of the mavenmixins; the only substantive difference is that it also tags the repo with the release version.

[source,bash]
----
pushd modules
----

Before doing so, update the `incode-parent` module's `pom.xml`, so that it references the (just released) non-SNAPSHOT version of the mavenmixins.

[NOTE]
====
TODO: should automate this editing, put into the `release.sh` script instead.
====

Commit the changes.

Then, release using:


[source,bash]
----
sh release.sh $INCODEREL \
              $INCODENEXT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

If the script completes successfully, then push changes and the tag:

[source]
----
git push origin master && git push origin $INCODEREL
popd
----

=== Recreating the archetype

The quickstart archetype is re-created for each release from the current quickstart application.
The generated archetype is then released by deploying up to Maven Central.

If necessary, setup environment variables:

[source,bash]
----
export INCODEREL=1.15.1
export INCODENEXT=1.16.0-SNAPSHOT

env | grep ^INCODE
----


Then, switch to the quickstart _application_:

[source,bash]
----
pushd ex/app/quickstart
----

Now check the application source code:

* Confirm that the parent `pom.xml` of the quickstart application inherits from the release version of `org.incode:incode-parent`.
For example:

+
[source,xml]
----
<parent>
    <groupId>org.incode</groupId>
    <artifactId>incode-parent</artifactId>
    <version>1.15.1</version>
    <relativePath/>
</parent>
----

* Also check that the parent `pom.xml` references the release (non-SNAPSHOT) versions of `isis.version`:

+
[source,xml]
----
<properties>
    <isis.version>1.15.1</isis.version>
    ...
</properties>
----

* Finally, ensure that the optional modules are *commented in*.

+
Search for the phrase _"Uncomment to include example modules"_


Staying in the same directory, recreate using:

[source,bash]
----
sh ../../arch/recreate-archetype.sh $INCODEREL
----

Finally, commit any changes:

[source,bash]
----
popd
git commit -am "recreates archetype for $INCODEREL"
----


=== Releasing the archetype

We release in three steps:

* build the archetype locally (analogous to `mvn release:prepare`)
* check that an application can be built from the archetype
* deploy the archetype (using `mvn deploy`).


==== Prepare the archetype

The archetype is prepared using:

[source,bash]
----
pushd ex/arch/quickstart
sh ../release-prepare.sh $INCODEREL
popd
----


==== Testing the archetype

In a _different session_:

First, setup environment variables:

[source,bash]
----
export INCODEREL=1.15.1
export INCODETMP=/c/tmp    # or as required
export INCODEART=quickstart
env | grep INCODE | sort
----

then:

[source,bash]
----
rm -rf $INCODETMP/test-$INCODEART

mkdir $INCODETMP/test-$INCODEART
cd $INCODETMP/test-$INCODEART
----

then:

[source,bash]
----
mvn archetype:generate  \
    -D archetypeGroupId=org.incode.platform.archetype \
    -D archetypeArtifactId=quickstart-archetype \
    -D archetypeVersion=$INCODEREL \
    -D groupId=com.mycompany \
    -D artifactId=myapp \
    -D version=1.0-SNAPSHOT \
    -D archetypeCatalog=local \
    -B
----

and build and run using:

[source,bash]
----
cd myapp
mvn clean install

mvn -pl webapp jetty:run \
    -Disis.appManifest=domainapp.appdefn.DomainAppAppManifestWithFixtures
----

Login using sven/pass.
The application generated should be the xref:../quickstart/quickstart.adoc#[Quickstart app].


==== Deploying the archetype

Back in the original session (in the `ex/arch/quickstart` directory), the archetype is released (deployed to Maven Central) using:

[source,bash]
----
pushd ex/arch/quickstart
sh ../release-deploy.sh \
              $INCODENEXT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

This script should automatically commit changes.
To finish up, just push:

[source,bash]
----
popd
git push
----



== Release an Interim Build

If you have commit access to this project (or a fork of your own) then you can create interim releases using the `interim-release.sh` script.

The idea is that this will - in a new branch - update the artifacts with a timestamped version (eg `1.15.0.20170927-0738`).
It then pushes the branch (and a tag) to the specified remote.

A CI server such as Jenkins can monitor the branches matching the wildcard `origin/interim/*` and create a build.
These artifacts can then be published to a snapshot repository.

For example:


[source,bash]
----
pushd modules
sh interim-release.sh $INCODEREL origin
popd
----

where

* `origin` is the name of the remote to which you have permissions to write to.




== Release Snapshot

To deploy a snapshot (to Sonatype's snapshot repo), use:

[source]
----
pushd modules
mvn clean deploy
popd
----

The artifacts should be available in Sonatype's
https://oss.sonatype.org/content/repositories/snapshots[Snapshot Repo].



== Docs & website

The website resides in the `adocs` directory:

* `documentation/` is the source for website itself (Asciidoctor)
* `template/` is the HTML template
* `search/` holds node.js Javascript files to index the built site so that it is searchable

The website is published to the link:https://github.com/incodehq/incodehq.github.io[incodehq/incodehq.github.io] github repository; a `CNAME` file (in the root directory) maps this to http://platform.catalog.org.

To publish, this repository must also be cloned to your local computer.
The scripts assume that the `incode-platform` repository (ie this repo) and the `incodehq.github.io` repository cloned at the same level, eg:

[monotree]
----
+
 + incodehq
  - incode-platform
  - incodehq.github.io
----

=== Prerequisites

Make sure that you've checked out the `incodehq/incodehq.github.io` repository alongside this one (see discussion above).

You'll also need to install:

* node (v7.10.0 or later) ... used to build the search index
* python 3 ... used to preview

The actual website generation uses AsciidoctorJ, which is called by Maven plugin.
There are no other software prereqs.

Normally you'll want to work in the `adocs/documentation` directory:

[source,bash]
----
pushd adocs/documentation
----


=== Previewing the website


To do a quick build the website and preview locally, use:

[source,bash]
----
sh preview-html.sh
----

This builds the HTML and the search index, but omits building the PDFs.
To enable you to preview the generated site, it starts a (python) webserver to browse.

To also build the PDFs, use:

[source,bash]
----
sh preview-html.sh
----



=== Publishing the website



When you are ready to publish the website, use:

[source,bash]
----
sh publish.sh
----

This will remove all files in the `incodeh.github.io` directory and replace with the latest build.


To check everything is ok:

[source,bash]
----
pushd ../../../incodehq.github.io
sh preview.sh
----

If all looks ok, then just push the changes:

[source,bash]
----
git push
----

