[[committers-guide]]
= Committers Guide
:_basedir: ../../
:_imagesdir: images/
:toc:
:generate_pdf:


This guide contains procedures to be performed by committers/maintainers of this codebase.


== Release process

This section describes the steps to release the platform to Maven central.
There are four stages:

* release the maven mixins

* release the modules

* recreate the quickstart archetype (referencing the just-released modules)

* release the quickstart archetype

The release process uses Sonatype's OSS support (see
link:http://central.sonatype.org/pages/apache-maven.html[user guide]); our thanks to them for providing this service.


=== Prereqs

First, set the `$INCODEREL` environment variable to the release.
Generally speaking this should correspond to the version of Apache Isis.

[source,bash]
----
export $INCODEREL=1.15.0
----


==  Maven deploy notes


=== Release to Sonatype's Snapshot Repo

To deploy a snapshot, use:

[source]
----
pushd dom
mvn clean deploy
popd
----

The artifacts should be available in Sonatype's
https://oss.sonatype.org/content/repositories/snapshots[Snapshot Repo].


=== Release an Interim Build

If you have commit access to this project (or a fork of your own) then you can create interim releases using the `interim-release.sh` script.

The idea is that this will - in a new branch - update the `dom/pom.xml` with a timestamped version (eg `1.14.0.20170227-0738`).
It then pushes the branch (and a tag) to the specified remote.

A CI server such as Jenkins can monitor the branches matching the wildcard `origin/interim/*` and create a build.
These artifacts can then be published to a snapshot repository.

For example:

[source]
----
sh interim-release.sh 1.14.0 origin
----

where

* `1.14.0` is the base release
* `origin` is the name of the remote to which you have permissions to write to.



=== Release to Maven Central

The `release.sh` script automates the release process. It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 1.14.0 \
              1.15.0-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where
* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the `pgp-maven-plugin`'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master && git push origin 1.14.0
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue
before trying again.  Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the
`autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).  You may want
to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].



=== Recreating the archetype

[source,bash]
----
export $INCODEREL=1.15.0
cd ex/app/quickstart
sh ../../../scripts/recreate-archetype.sh
----

