
package org.incode.domainapp.example.publishmq.externalsystemadapter.fakeserver;

import javax.xml.ws.Endpoint;

/**
 * This class was originally generated by Apache CXF 3.1.1
 * 2015-06-19T16:26:16.637+01:00
 * Generated source version: 3.1.1
 *
 * Renamed from DemoObject_DemoObjectOverSOAP_Server, placed in src/test/java
 */
public class ExternalSystemFakeServerHarness {

    protected ExternalSystemFakeServerHarness() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ExternalSystemFakeServer();
        String address = "http://localhost:8080/soap/ExternalSystemAdapter/DemoObject";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ExternalSystemFakeServerHarness();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
