
package org.isisaddons.module.publishmq.soapsubscriber;

import javax.xml.ws.Endpoint;

import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;
import org.apache.cxf.jaxws.EndpointImpl;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-06-19T09:40:50.440+01:00
 * Generated source version: 2.7.3
 * 
 */
 
public class DemoObject_DemoObjectOverSOAP_Server{

    private final EndpointImpl ep;

    protected DemoObject_DemoObjectOverSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new DemoObjectImpl();
        String address = "http://localhost:9090/DemoObjectPort";
        ep = (EndpointImpl) Endpoint.publish(address, implementor);

        ep.getServer().getEndpoint().getInInterceptors().add(new LoggingInInterceptor());
        ep.getServer().getEndpoint().getOutInterceptors().add(new LoggingOutInterceptor());
    }

    public static void main(String args[]) throws Exception {
        new DemoObject_DemoObjectOverSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }

    public void stop() {
        ep.getServer().stop();
        ep.getServer().destroy();
    }

}
