
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.isisaddons.module.publishmq.soapsubscriber;

import java.util.logging.Logger;

import javax.annotation.Resource;
import javax.xml.ws.WebServiceContext;

import org.isisaddons.module.publishmq.soapsubscriber.demoobject.DemoObject;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-19T16:26:16.572+01:00
 * Generated source version: 3.1.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "DemoObjectService",
                      portName = "DemoObjectOverSOAP",
                      targetNamespace = "http://isisaddons.org/module/publishmq/soapsubscriber/DemoObject/",
                      wsdlLocation = "classpath:DemoObject.wsdl",
                      endpointInterface = "org.isisaddons.module.publishmq.soapsubscriber.demoobject.DemoObject")
                      
public class DemoObjectOverSOAPImpl implements DemoObject {

    /**
     * The WebServiceContext can be used to retrieve special attributes like the
     * user principal. Normally it is not needed
     */
    @Resource
    WebServiceContext wsContext;

    private static final Logger LOG = Logger.getLogger(DemoObjectOverSOAPImpl.class.getName());

    public String processed(String name,String description) {
        LOG.info("Executing operation processed");
        System.out.println(name);
        System.out.println(description);
        try {
            return "name: " + name + ", description:" + description;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
