[[lib-docrendering-stringinterpolator]]
= StringInterpolator Document Rendering Library
:_basedir: ../../../
:_imagesdir: images/

This module (`incode-module-docrendering-stringinterpolator`) provides an implementation of the Incode http://github.com/incodehq/incode-module-document[Document] module's `Renderer` interface using the (non-ASF) http://github.com/isisaddons/isis-module-stringinterpolator[Isis addons' stringinterpolator] module.


== API

The module provides three different implementations of `Renderer`:

* `RendererForStringInterpolator` which implements `RendererFromCharsToChars`
** useful for interpolating document names or simple text (eg an HTML email)
* `RendererForStringInterpolatorCaptureUrl` which implements `RendererFromCharsToBytes`
** interpolates to a URL, then uses the `UrlDownloaderService` (SPI service, discussed below) to download the URL and return its content as a `byte[]`.
For example, could be used to download a PDF or Word document.
* `RendererForStringInterpolatorPreviewAndCaptureUrl` which implements `RendererFromCharsToBytesWithPreviewToUrl`
** this is very similar to the previous renderer, but also provides access to the intermediary URL, thereby allowing the Document module to provide an action to preview the document.

These classes can be used as the `Renderer` implementation for a Document `RenderingStrategy`.
Subclasses of the `RenderingStrategyFSAbstract` fixture script can be used to create such an entity, eg:

* `RenderingStrategyFSForStringInterpolator` +
+
[source,java]
----
public class RenderingStrategyFSForStringInterpolator extends RenderingStrategyFSAbstract {
    public static final String REF = "SI";
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "String interpolate",
                DocumentNature.CHARACTERS,
                DocumentNature.CHARACTERS,
                RendererForStringInterpolator.class, executionContext);
    }
}
----

* `RenderingStrategyFSForStringInterpolatorCaptureUrl` +
+
[source,java]
----
public class RenderingStrategyFSForStringInterpolatorCaptureUrl extends RenderingStrategyFSAbstract {
    public static final String REF = "SINC";
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "String interpolate URL for Capture (no preview)",
                DocumentNature.CHARACTERS,
                DocumentNature.BYTES,
                RendererForStringInterpolatorCaptureUrl.class, executionContext);
    }
}
----

* `RenderingStrategyFSForStringInterpolatorPreviewAndCaptureUrl` +
+
[source,java]
----
public class RenderingStrategyFSForStringInterpolatorPreviewAndCaptureUrl extends RenderingStrategyFSAbstract {
    public static final String REF = "SIPC";
    @Override
    protected void execute(ExecutionContext executionContext) {
        upsertRenderingStrategy(
                REF,
                "String interpolate URL for Preview and Capture",
                DocumentNature.CHARACTERS,
                DocumentNature.BYTES,
                RendererForStringInterpolatorPreviewAndCaptureUrl.class, executionContext);
    }
}
----

The Incode http://github.com/incodehq/incode-module-document[document] module also allows ``RenderingStrategy``s to be created from the UI; it will "discover" all `Renderer` implementations from the classpath.

== SPI

The `RendererForStringInterpolatorCaptureUrl` and `RendererForStringInterpolatorPreviewAndCaptureUrl` renderer implementations both rely on the `UrlDownloaderService` to convert the interpolated URL string into an array of bytes.
This interface is defined as:

[source,java]
----
public interface UrlDownloaderService {
    public byte[] download(URL url) throws IOException;
    boolean canDownload(URL url);
}
----

The application consuming this module can provide its own implementation of this service, or may be able to use one of the implementations provided out-of-the-box by the module discussed below).


== SPI Implementations

The module provides two implementations of the `UrlDownloadService`.
The renderer will use the first service where `canDownload(...)` returns `true`.


=== UrlDownloaderUsingNtlmCredentials

(As its name suggests), the `UrlDownloaderUsingNtlmCredentials` implementation of the service is able to access a URL and provide NTLM (Active Directory) credentials.

It requires the following configuration options:

* `incode.module.docrendering.stringinterpolator.UrlDownloaderUsingNtlmCredentials.user`
* `incode.module.docrendering.stringinterpolator.UrlDownloaderUsingNtlmCredentials.password`
* `incode.module.docrendering.stringinterpolator.UrlDownloaderUsingNtlmCredentials.host`

The user should be provided in the format `DOMAIN/username` eg `ACME/jbloggs`.

If the configuration options are not provided, then the service is effectively ignored.

This service has a priority of 100 (`@DomainService#menuOrder="100"`).



=== UrlDownloaderService.SimpleUsingGuava (fallback)

The `UrlDownloaderService.SimpleUsingGuava` implementation of the service simply uses Guava to download from the URL, providing no credentials.
It is used as a fallback if no other service is able to download.



== How to configure/use

You can either use this module "out-of-the-box", or you can fork this repo and extend to your own requirements. 

=== "Out-of-the-box"

To use "out-of-the-box":

* update your classpath by adding this dependency in your dom project's `pom.xml`: +
+
[source,xml]
----
<dependency>
    <groupId>org.incode.module.docrendering</groupId>
    <artifactId>incode-module-docrendering-stringinterpolator-dom</artifactId>
    <version>1.14.0</version>
</dependency>
----

* in the `AppManifest`, update its `getModules()` method: +
+
[source,java]
----
@Override
public List<Class<?>> getModules() {
    return Arrays.asList(
            ...
            org.incode.module.docrendering.stringinterpolator.dom.StringInterpolatorDocRenderingModule.class,
    );
}
----

Notes:

* Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-docrendering-stringinterpolator-dom[Maven Central Repo].



==== "Out-of-the-box" (-SNAPSHOT)

If you want to use the current `-SNAPSHOT`, then the steps are the same as above, except:

* when updating the classpath, specify the appropriate -SNAPSHOT version:

[source,xml]
----
<version>1.14.0-SNAPSHOT</version>
----

* add the repository definition to pick up the most recent snapshot (we use the Cloudbees continuous integration service).  We suggest defining the repository in a `<profile>`:

[source,xml]
----
<profile>
    <id>cloudbees-snapshots</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>http://repository-estatio.forge.cloudbees.com/snapshot/</url>
            <releases>
                <enabled>false>/enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</profile>
----







== Known issues

None known at this time.






=== Dependencies

TODO: to update


