[[quickstart]]
= Quickstart
:_basedir: ../../
:_imagesdir: images/
:toc:
:generate_pdf:



The quickstart is a Maven archetype intended to be used as a template for new applications.

Like the Apache Isis framework's own link:http://isis.apache.org#guides/ugfun/ugfun.html#_ugfun_getting-started_simpleapp-archetype[simpleapp archetype], the application provides a `SimpleObject` to adapt and copy, along with supporting unit tests, integration tests and BDD (cucumber) specs.

The application generated from the archetype is also preconfigured with the dependencies for all of the modules available in the Incode Platform, with xref:../modules/spi/audit/spi-audit.adoc#[auditing], xref:../modules/spi/command/spi-command.adoc#[command] profiling, xref:../modules/spi/security/spi-security.adoc#[security], xref:../modules/ext/flywaydb/ext-flywaydb.adoc#[flywaydb] and (feature) xref:../modules/ext/togglz/ext-togglz.adoc#[togglz] enabled by default.
The application also configures the _Quartz scheduler_ for background scheduling, and the _Jolokia_ servlet, allowing consoles such as _hawt.io_ to monitor the internal state of the webapp.

The generated application also includes example code to:

* xref:quickstart-with-embedded-camel.adoc#[bootstrap] a _Spring Framework_ context alongside the Apache Isis framework, hosting embedded _Apache Camel_ and _Apache ActiveMQ_ instances

* xref:quickstart-with-example-usage.adoc#[demonstrate usage] of the various modules within the Incode Platform.

These can be easily included or excluded just by commenting in/out small sections of code.


include::_quickstart_prerequisites.adoc[leveloffset=+1]

include::_quickstart_running-the-archetype.adoc[leveloffset=+1]

include::_quickstart_project-structure.adoc[leveloffset=+1]

include::_quickstart_building.adoc[leveloffset=+1]

include::_quickstart_running.adoc[leveloffset=+1]

include::_quickstart_using-an-external-database.adoc[leveloffset=+1]

include::_quickstart_modules.adoc[leveloffset=+1]

include::_quickstart_dynamic-reloading.adoc[leveloffset=+1]

include::_quickstart_maven-mixins.adoc[leveloffset=+1]



