[[index]]
= Incode Platform
:_basedir: ./
:_imagesdir: images/
:notoc: true

pass:[<br/>]

The Incode Platform provides a number of _modules_ for use with the link:http://isis.apache.org[Apache Isis] framework.
The platform also provides a _"quickstart"_ app which can be used to quickly set up your own pre-configured applications.



[[quickstart]]
== Quickstart

The xref:quickstart/quickstart.adoc#[quickstart app] is a Maven archetype intended to be used as a starting point for new applications.

[source,bash]
----
mvn archetype:generate  \
    -D archetypeGroupId=org.incode.platform.archetype \
    -D archetypeArtifactId=quickstart-archetype \
    -D archetypeVersion=1.15.1.1 \
    -D groupId=com.mycompany \
    -D artifactId=myapp \
    -D version=1.0-SNAPSHOT \
    -B
----
Like the Apache Isis framework's own link:http://isis.apache.org#guides/ugfun/ugfun.html#_ugfun_getting-started_simpleapp-archetype[simpleapp archetype], the application provides a `SimpleObject` to adapt and copy, along with supporting unit tests, integration tests and BDD (cucumber) specs.

The application generated from the archetype is also preconfigured with the dependencies for all of the modules available in the Incode Platform, with xref:modules/spi/audit/spi-audit.adoc#[auditing], xref:modules/spi/command/spi-command.adoc#[command] profiling, message xref:modules/spi/publishmq/spi-publishmq.adoc#[publishing], xref:modules/spi/security/spi-security.adoc#[security], xref:modules/ext/flywaydb/ext-flywaydb.adoc#[flywaydb], xref:modules/ext/quartz/ext-quartz.adoc#[quartz] scheduler and (feature) xref:modules/ext/togglz/ext-togglz.adoc#[togglz] enabled by default.
The application also configures the _Jolokia_ servlet to allow consoles such as _hawt.io_ to monitor the internal state of the webapp.


[[modules]]
== Modules

Select the modules you need and use them "out of the box", or fork the repo and use the source code as a starting point to meet your own requirements.
Most modules are independent of others, with the README for each explaining how to configure your application to use it.

The modules fall into six broad categories, summarised in the table below:

[cols="^1a,^1a,^1a,^1a,^1a,^1a,^1a", options="header,footer", frame="all", grid="none"]
|===

2.+^.^| xref:modules/lib/lib.adoc#[_Libraries_]
^.^| xref:modules/spi/spi.adoc#[_SPI +
Implementations_]
^.^| xref:modules/wkt/wkt.adoc#[_Wicket Components_]
^.^| xref:modules/ext/ext.adoc#[_Extensions_]
2.+^.^| xref:modules/dom/dom.adoc#[_Example +
Subdomains & Libraries_]


|

xref:modules/lib/base/lib-base.adoc#[Base]

xref:modules/lib/docx/lib-docx.adoc#[Docx (MS Word)]

xref:modules/lib/excel/lib-excel.adoc#[Excel]

xref:modules/lib/fakedata/lib-fakedata.adoc#[Fake Data]

xref:modules/lib/fixturesupport/lib-fixturesupport.adoc#[Fixture Support]

xref:modules/lib/freemarker/lib-freemarker.adoc#[FreeMarker]

xref:modules/lib/integtestsupport/lib-integtestsupport.adoc#[IntegTesting Support]

|

xref:modules/lib/pdfbox/lib-pdfbox.adoc#[PDFBox]

xref:modules/lib/poly/lib-poly.adoc#[Polymorphic Associations]

xref:modules/lib/servletapi/lib-servletapi.adoc#[Servlet API]

xref:modules/lib/stringinterpolator/lib-stringinterpolator.adoc#[StringInterpolator (OGNL)]

xref:modules/lib/unittestsupport/lib-unittestsupport.adoc#[Unit Testing Support]

xref:modules/lib/xdocreport/lib-xdocreport.adoc#[XDocReport]

|

xref:modules/spi/audit/spi-audit.adoc#[Audit]

xref:modules/spi/command/spi-command.adoc#[Command]

xref:modules/spi/publishmq/spi-publishmq.adoc#[Publishmq]

xref:modules/spi/security/spi-security.adoc#[Security]

xref:modules/spi/sessionlogger/spi-sessionlogger.adoc#[Sessionlogger]

|

xref:modules/wkt/excel/wkt-excel.adoc#[Excel]

xref:modules/wkt/fullcalendar2/wkt-fullcalendar2.adoc#[Fullcalendar2]

xref:modules/wkt/gmap3/wkt-gmap3.adoc#[Gmap3]

xref:modules/wkt/pdfjs/wkt-pdfjs.adoc#[Pdfjs]

xref:modules/wkt/summernote/wkt-summernote.adoc#[Summernote]

xref:modules/wkt/wickedcharts/wkt-wickedcharts.adoc#[Wickedcharts]



| xref:modules/ext/flywaydb/ext-flywaydb.adoc#[FlywayDB]

xref:modules/ext/quartz/ext-quartz.adoc#[Quartz]

xref:modules/ext/togglz/ext-togglz.adoc#[Togglz]


|

xref:modules/dom/alias/dom-alias.adoc#[Alias]

xref:modules/dom/classification/dom-classification.adoc#[Classification]

xref:modules/dom/commchannel/dom-commchannel.adoc#[Comm Channel]

xref:modules/dom/communications/dom-communications.adoc#[Communications]

xref:modules/dom/country/dom-country.adoc#[Country]

xref:modules/dom/docfragment/dom-docfragment.adoc#[Doc Fragment]

xref:modules/dom/docrendering-freemarker/lib-docrendering-freemarker.adoc#[Freemarker DocRendering]

|
xref:modules/dom/docrendering-stringinterpolator/lib-docrendering-stringinterpolator.adoc#[Stringinterpolator DoRendering]

xref:modules/dom/docrendering-xdocreport/lib-docrendering-xdocreport.adoc#[Xdocreport DocRendering]


xref:modules/dom/document/dom-document.adoc#[Document]

xref:modules/dom/note/dom-note.adoc#[Note]

xref:modules/dom/settings/dom-settings.adoc#[Settings]

xref:modules/dom/tags/dom-tags.adoc#[Tags]



|===



