[[index]]
= Incode Platform
:_basedir: ./
:_imagesdir: images/
:notoc: true

pass:[<br/>]

The Incode Platform provides a number of _modules_ for use with the link:http://isis.apache.org[Apache Isis] framework.
These are all released as ready-to-use binaries.

The platform also provides a _"quickstart"_ Maven archetype which can be used to quickly set up your own pre-configured applications.

There are also a number of companion/supporting websites, accessible from the "Other Resources" menu, above.



[[quickstart]]
== Quickstart

The xref:quickstart/quickstart.adoc#[quickstart app] is a Maven archetype intended to be used as a starting point for new applications.

[source,bash]
----
mvn archetype:generate  \
    -D archetypeGroupId=org.incode.platform.archetype \
    -D archetypeArtifactId=quickstart-archetype \
    -D archetypeVersion=1.16.2 \
    -D groupId=com.mycompany \
    -D artifactId=myapp \
    -D version=1.0-SNAPSHOT \
    -B
----
Like the Apache Isis framework's own link:http://isis.apache.org#guides/ugfun/ugfun.html#_ugfun_getting-started_simpleapp-archetype[simpleapp archetype], the application provides a `SimpleObject` to adapt and copy, along with supporting unit tests, integration tests and BDD (cucumber) specs.

The application generated from the archetype is also preconfigured with the dependencies for all of the modules available in the Incode Platform, with xref:modules/spi/audit/spi-audit.adoc#[auditing], xref:modules/spi/command/spi-command.adoc#[command] profiling, message xref:modules/spi/publishmq/spi-publishmq.adoc#[publishing], xref:modules/spi/security/spi-security.adoc#[security], xref:modules/ext/flywaydb/ext-flywaydb.adoc#[flywaydb], xref:modules/ext/quartz/ext-quartz.adoc#[quartz] scheduler and (feature) xref:modules/ext/togglz/ext-togglz.adoc#[togglz] enabled by default.
The application also configures the _Jolokia_ servlet to allow consoles such as _hawt.io_ to monitor the internal state of the webapp.


[[modules]]
== Modules

Select the modules you need and use them "out of the box", or fork the repo and use the source code as a starting point to meet your own requirements.
Most modules are independent of others, with the README for each explaining how to configure your application to use it.

The modules fall into six broad categories, summarised in the table below:

[cols="^1a,^1a,^1a,^1a,^1a,^1a,^1a", options="header,footer", frame="all", grid="none"]
|===

^.^| xref:modules/dom/dom.adoc#[_(Sub)domains_]
^.^| xref:modules/ext/ext.adoc#[_Extensions_]
2.+^.^| xref:modules/lib/lib.adoc#[_Libraries_]
^.^| xref:modules/wkt/mml.adoc#[_Metamodel +
Facets_]
^.^| xref:modules/spi/spi.adoc#[_SPI +
Implementations_]
^.^| xref:modules/wkt/wkt.adoc#[_Wicket Components_]

| xref:modules/dom/settings/dom-settings.adoc#[Settings]

| xref:modules/ext/flywaydb/ext-flywaydb.adoc#[FlywayDB]

xref:modules/ext/quartz/ext-quartz.adoc#[Quartz]

xref:modules/ext/togglz/ext-togglz.adoc#[Togglz]
|

xref:modules/lib/base/lib-base.adoc#[Base]

xref:modules/lib/docx/lib-docx.adoc#[Docx (MS Word)]

xref:modules/lib/excel/lib-excel.adoc#[Excel]

xref:modules/lib/fakedata/lib-fakedata.adoc#[Fake Data]

xref:modules/lib/fixturesupport/lib-fixturesupport.adoc#[Fixture Support]

xref:modules/lib/freemarker/lib-freemarker.adoc#[FreeMarker]

xref:modules/lib/integtestsupport/lib-integtestsupport.adoc#[IntegTesting Support]

xref:modules/lib/jaxrsclient/lib-jaxrsclient.adoc#[JAX-RS Client]


|

xref:modules/lib/pdfbox/lib-pdfbox.adoc#[PDFBox]

xref:modules/lib/poly/lib-poly.adoc#[Polymorphic Associations]

xref:modules/lib/servletapi/lib-servletapi.adoc#[Servlet API]

xref:modules/lib/slack/lib-slack.adoc#[Slack]

xref:modules/lib/stringinterpolator/lib-stringinterpolator.adoc#[StringInterpolator (OGNL)]

xref:modules/lib/unittestsupport/lib-unittestsupport.adoc#[Unit Testing Support]

xref:modules/lib/xdocreport/lib-xdocreport.adoc#[XDocReport]

xref:modules/lib/zip/lib-zip.adoc#[Zip]
| xref:modules/mml/paraname8/mml-paraname8.adoc#[Paraname8]

|

xref:modules/spi/audit/spi-audit.adoc#[Audit]

xref:modules/spi/command/spi-command.adoc#[Command Replay]

xref:modules/spi/errorrptjira/spi-errorrptjira.adoc#[Error Report (JIRA)]

xref:modules/spi/errorrptslack/spi-errorrptslack.adoc#[Error Report (Slack)]

xref:modules/spi/publishmq/spi-publishmq.adoc#[Publishmq]

xref:modules/spi/security/spi-security.adoc#[Security]

xref:modules/spi/sessionlogger/spi-sessionlogger.adoc#[Sessionlogger]

xref:modules/spi/userimpersonate/spi-userimpersonate.adoc#[User Impersonation]


|

xref:modules/wkt/excel/wkt-excel.adoc#[Excel]

xref:modules/wkt/fullcalendar2/wkt-fullcalendar2.adoc#[Fullcalendar2]

xref:modules/wkt/gmap3/wkt-gmap3.adoc#[Gmap3]

xref:modules/wkt/pdfjs/wkt-pdfjs.adoc#[Pdfjs]

xref:modules/wkt/summernote/wkt-summernote.adoc#[Summernote]

xref:modules/wkt/wickedcharts/wkt-wickedcharts.adoc#[Wickedcharts]



|===




[[parent-pom]]
== Parent POM

The `org.incode:incode-parent` parent POM declares all of the platform modules.
It can either be inherited from, or added as a dependency:

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <group>org.incode</group>
        <artifactId>incode-parent</artifactId>
        <version>1.6.2</version>
        <scope>import</scope>
        <type>pom</type>
    </dependencies>
</dependencyManagement>
----


[[interim-releases]]
== Interim Releases

Interim releases of the modules are available at link:https://repo.incode.cloud[].

Available interim releases can be found using link:https://repo.incode.cloud/#browse/search/maven=attributes.maven2.artifactId%3Dincode-parent[]

To use interim releases, add this profile:

[source,xml]
----
<profile>
    <id>incode-cloud-maven</id>
    <activation>
        <property>
            <name>!skip.incode-cloud-maven</name>
        </property>
    </activation>
    <repositories>
        <repository>
            <id>incode-cloud-maven</id>
            <url>https://repo.incode.cloud/repository/maven/</url>
            <name>Incode Cloud (maven)</name>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
                <checksumPolicy>fail</checksumPolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
                <updatePolicy>always</updatePolicy>
                <checksumPolicy>fail</checksumPolicy>
            </snapshots>
            <layout>default</layout>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>incode-cloud-maven</id>
            <name>Incode Cloud (maven)</name>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
                <checksumPolicy>fail</checksumPolicy>
            </releases>
            <url>https://repo.incode.cloud/repository/maven/</url>
            <layout>default</layout>
        </pluginRepository>
    </pluginRepositories>
</profile>
----

Alternatively, inherit from either `org.incode:incode-parent` or from _its_ parent, `https://github.com/incodehq/incode-build[org.incode:incode-build]`; the latter declares this Maven repository.


