[[lib-integtestsupport]]
= Integration Testing Support Library
:_basedir: ../../../
:_imagesdir: images/
:generate_pdf:
:toc:

This module (`incode-module-integtestsupport`) provides a set of testing utilities to support integration testing.



== How to configure/use

=== Classpath

Update your classpath by adding this dependency in your dom project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>org.incode.module.integtestsupport</groupId>
    <artifactId>incode-module-integtestsupport-dom</artifactId>
    <version>1.15.1.1</version>
    <scope>test</scope>
</dependency>
----

Check for later releases by searching http://search.maven.org/#search|ga|1|incode-module-integtestsupport-dom[Maven Central Repo].

For instructions on how to use the latest `-SNAPSHOT`, see the xref:../../../pages/contributors-guide.adoc#[contributors guide].





== Known issues

None known at this time.




== Dependencies

Maven can report modules dependencies using:

[source,bash]
----
mvn dependency:list -o -pl modules/lib/integtestsupport/impl -D excludeTransitive=true
----

which, excluding Incode Platform and Apache Isis modules, returns these compile/runtime dependencies:


[source,bash]
----
junit:junit:jar:4.12:compile
org.jmock:jmock:jar:2.6.0:compile
org.jmock:jmock-junit4:jar:2.6.0:compile
org.picocontainer:picocontainer:jar:2.15:compile
org.reflections:reflections:jar:0.9.10:compile
org.assertj:assertj-core:jar:3.6.2:compile
com.danhaywood.java:danhaywood-java-assertjext:jar:0.1.0
----

From the Incode Platform it uses:

* xref:../../lib/base/lib-base.adoc#[base library] module
* xref:../../lib/base/lib-fakedata.adoc#[fakedata library] module
* xref:../../lib/base/lib-fixturesupport.adoc#[fixturesupport library] module

